import asyncio
from loguru import logger

from instacrud.model.system_model import AiModel, AiServiceProvider, Tier
from instacrud.database import init_system_db

# -------------------------------------------------------------------
# Tiers Data
# -------------------------------------------------------------------
TIERS = [
    {"tier": 1, "name": "Free", "code": "free", "usage": 0.01, "active": True},
    {"tier": 5, "name": "Pro", "code": "pro", "usage": 0.4, "active": True},
    {"tier": 10, "name": "Premium", "code": "premium", "usage": 1, "active": True},
    {"tier": 15, "name": "Platinum", "code": "platinum", "usage": 2.5, "active": True},
]

# -------------------------------------------------------------------
# AI Models Data
# -------------------------------------------------------------------
# Each model entry is a dict with the following fields:
#
#   service           – AiServiceProvider enum (OPEN_AI, CLAUDE, DEEP_INFRA, OLLAMA)
#   name              – Human-readable display name shown in the UI
#   model_identifier  – Exact API model ID sent to the provider
#   temperature       – Sampling temperature (omit for models that don't support it, e.g. GPT-5 series)
#   max_tokens        – Maximum output token limit for this model
#   credits           – Internal credit cost charged per request (billing unit = USD × 10 000):
#                         • LLMs:      cost of a typical chat (4 000 input + 1 000 output tokens) × 10 000
#                         • Images:    cost of one generated image × 10 000  (= input_tokens_cost × 10 000)
#                         • Embeddings: flat minimum of 1 (actual token cost is negligible)
#   input_tokens_cost – Provider's cost in USD per 1 000 input tokens
#   output_tokens_cost– Provider's cost in USD per 1 000 output tokens (0.0 for image/embedding models billed per call)
#   completion        – True if the model supports text/chat completion
#   embedding         – True if the model produces vector embeddings
#   image_completion  – True if the model can accept image input (vision)
#   image_generation  – True if the model generates images as output
#   reasoning         – True if the model has built-in chain-of-thought / reasoning mode
#   enabled           – Whether the model is active and selectable by users
#   rank              – Sort order within its service group (lower = shown first)
#   tier              – Minimum subscription tier required (matches Tier.tier values: 1=Free, 5=Pro, …)
#   icon              – URL or path to the provider logo displayed in the UI
#   params            – (optional) Extra provider-specific settings, e.g. image resolution options
# -------------------------------------------------------------------
ICON_OPENAI = "/icons/openai.svg"
ICON_ANTHROPIC = "https://cdn.simpleicons.org/anthropic/000000"
ICON_DEEPINFRA = "https://deepinfra.com/favicon.ico"
ICON_OLLAMA = "https://cdn.simpleicons.org/ollama/000000"

AI_MODELS = [
    # ===================== OPENAI – COMPLETION =====================
    # Note: GPT-5 series models do NOT support temperature parameter
    # They only support default temperature of 1
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5.2",
        "model_identifier": "gpt-5.2",
        "max_tokens": 128000,
        "credits": 150,
        "input_tokens_cost": 1.25,
        "output_tokens_cost": 10.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 25,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5.1",
        "model_identifier": "gpt-5.1",
        "max_tokens": 128000,
        "credits": 150,
        "input_tokens_cost": 1.25,
        "output_tokens_cost": 10.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 30,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5",
        "model_identifier": "gpt-5",
        "max_tokens": 128000,
        "credits": 150,
        "input_tokens_cost": 1.25,
        "output_tokens_cost": 10.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 35,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-5 Mini",
        "model_identifier": "gpt-5-mini",
        "max_tokens": 128000,
        "credits": 30,
        "input_tokens_cost": 0.25,
        "output_tokens_cost": 2.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 35,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-4 Turbo",
        "model_identifier": "gpt-4-turbo-2024-04-09",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 700,
        "input_tokens_cost": 10.0,
        "output_tokens_cost": 30.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 20,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-4",
        "model_identifier": "gpt-4-0613",
        "temperature": 0.7,
        "max_tokens": 8192,
        "credits": 1800,
        "input_tokens_cost": 30.0,
        "output_tokens_cost": 60.0,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT-3.5 Turbo",
        "model_identifier": "gpt-3.5-turbo",
        "temperature": 0.7,
        "max_tokens": 4096,
        "credits": 35,
        "input_tokens_cost": 0.5,
        "output_tokens_cost": 1.5,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== OPENAI – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "Embedding 3 Small",
        "model_identifier": "text-embedding-3-small",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.02,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 15,
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "Embedding 3 Large",
        "model_identifier": "text-embedding-3-large",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.13,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 25,
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== OPENAI – IMAGE =====================
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "DALL·E 3",
        "model_identifier": "dall-e-3",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.08,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 20,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1792x1024", "1024x1792"],
            "quality": ["standard", "hd"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 1",
        "model_identifier": "gpt-image-1",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.08,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 80,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },
    {
        "service": AiServiceProvider.OPEN_AI,
        "name": "GPT Image 1.5",
        "model_identifier": "gpt-image-1.5",
        "credits": 500,
        "input_tokens_cost": 0.05,
        "output_tokens_cost": 0.1,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 90,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1024x1536", "1536x1024"],
            "quality": ["low", "medium", "high"]
        },
        "tier": 5,
        "icon": ICON_OPENAI,
    },

    # ===================== CLAUDE – COMPLETION =====================
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 4.5 Haiku",
        "model_identifier": "claude-haiku-4-5",
        "temperature": 0.7,
        "max_tokens": 64000,
        "credits": 90,
        "input_tokens_cost": 1.0,
        "output_tokens_cost": 5.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 25,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 4.5 Sonnet",
        "model_identifier": "claude-sonnet-4-5",
        "temperature": 0.7,
        "max_tokens": 64000,
        "credits": 270,
        "input_tokens_cost": 3.0,
        "output_tokens_cost": 15.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 12,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },
    {
        "service": AiServiceProvider.CLAUDE,
        "name": "Claude 4.5 Opus",
        "model_identifier": "claude-opus-4-5",
        "temperature": 0.7,
        "max_tokens": 64000,
        "credits": 450,
        "input_tokens_cost": 5.0,
        "output_tokens_cost": 25.0,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 18,
        "tier": 5,
        "icon": ICON_ANTHROPIC,
    },

    # ===================== DEEPINFRA – COMPLETION =====================
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 3.1 8B",
        "model_identifier": "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 2,
        "input_tokens_cost": 0.03,
        "output_tokens_cost": 0.05,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 50,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 3.3 70B",
        "model_identifier": "meta-llama/Llama-3.3-70B-Instruct",
        "temperature": 0.7,
        "max_tokens": 128000,
        "credits": 8,
        "input_tokens_cost": 0.1,
        "output_tokens_cost": 0.32,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 3.1 405B",
        "model_identifier": "meta-llama/Meta-Llama-3.1-405B-Instruct",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 135,
        "input_tokens_cost": 2.70,
        "output_tokens_cost": 2.70,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 60,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 4 Scout",
        "model_identifier": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "temperature": 0.7,
        "max_tokens": 320000,
        "credits": 7,
        "input_tokens_cost": 0.08,
        "output_tokens_cost": 0.3,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 70,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "LLaMA 4 Maverick",
        "model_identifier": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        "temperature": 0.7,
        "max_tokens": 1000000,
        "credits": 12,
        "input_tokens_cost": 0.15,
        "output_tokens_cost": 0.6,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 75,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "DeepSeek V3",
        "model_identifier": "deepseek-ai/DeepSeek-V3",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 22,
        "input_tokens_cost": 0.32,
        "output_tokens_cost": 0.89,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 5,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Kimi K2.5",
        "model_identifier": "moonshotai/Kimi-K2.5",
        "temperature": 0.7,
        "max_tokens": 262144,
        "credits": 41,
        "input_tokens_cost": 0.45,
        "output_tokens_cost": 2.25,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 10,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Kimi K2 Thinking",
        "model_identifier": "moonshotai/Kimi-K2-Thinking",
        "max_tokens": 131072,
        "credits": 39,
        "input_tokens_cost": 0.47,
        "output_tokens_cost": 2.00,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 15,
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== DEEPINFRA – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "BGE-M3 Multi",
        "model_identifier": "BAAI/bge-m3-multi",
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Multilingual E5 Large",
        "model_identifier": "intfloat/multilingual-e5-large",
        "max_tokens": 512,
        "credits": 1,
        "input_tokens_cost": 0.01,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 60,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3 Embedding 0.6B",
        "model_identifier": "Qwen/Qwen3-Embedding-0.6B-batch",
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.005,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen3 Embedding 8B",
        "model_identifier": "Qwen/Qwen3-Embedding-8B",
        "max_tokens": 32768,
        "credits": 1,
        "input_tokens_cost": 0.010,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 35,
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== DEEPINFRA – IMAGE =====================
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 2 Max",
        "model_identifier": "black-forest-labs/FLUX-2-max",
        "credits": 700,
        "input_tokens_cost": 0.07,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 20,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 2 Dev",
        "model_identifier": "black-forest-labs/FLUX-2-dev",
        "credits": 200,
        "input_tokens_cost": 0.02,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 25,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 1 Dev",
        "model_identifier": "black-forest-labs/FLUX-1-dev",
        "credits": 180,
        "input_tokens_cost": 0.018,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 30,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "FLUX 1 Schnell",
        "model_identifier": "black-forest-labs/FLUX-1-schnell",
        "credits": 10,
        "input_tokens_cost": 0.001,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 35,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"],
            "max_resolution": "1440x1440"
        },
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "SDXL Turbo",
        "model_identifier": "stabilityai/sdxl-turbo",
        "credits": 5,
        "input_tokens_cost": 0.0005,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"]
        },
        "tier": 1,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Bria 3.2",
        "model_identifier": "Bria/Bria-3.2",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 45,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1280x768", "1344x768", "832x1216", "1152x832", "1216x832", "960x1088"]
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Bria 3.2 Vector",
        "model_identifier": "Bria/Bria-3.2-vector",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 46,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024", "1280x768", "1344x768", "832x1216", "1152x832", "1216x832", "960x1088"]
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Qwen Image Edit",
        "model_identifier": "Qwen/Qwen-Image-Edit",
        "credits": 250,
        "input_tokens_cost": 0.025,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": True,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 50,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["any"]
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },
    {
        "service": AiServiceProvider.DEEP_INFRA,
        "name": "Seedream 4",
        "model_identifier": "ByteDance/Seedream-4",
        "credits": 400,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": False,
        "image_completion": False,
        "image_generation": True,
        "reasoning": False,
        "enabled": True,
        "rank": 55,
        "params": {
            "default_resolution": "1024x1024",
            "supported_resolutions": ["1024x1024","1728x3072","2048x2048","2304x4096","3072x1728","3840x1600","4096x2304","4096x4096"],
        },
        "tier": 5,
        "icon": ICON_DEEPINFRA,
    },

    # ===================== OLLAMA – COMPLETION =====================
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Mixtral 8x7B",
        "model_identifier": "mixtral:latest",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 27,
        "input_tokens_cost": 0.54,
        "output_tokens_cost": 0.54,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 50,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Mistral 7B",
        "model_identifier": "mistral:latest",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 60,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Dolphin Mixtral 8x7B",
        "model_identifier": "dolphin-mixtral:latest",
        "temperature": 0.7,
        "max_tokens": 32768,
        "credits": 27,
        "input_tokens_cost": 0.54,
        "output_tokens_cost": 0.54,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 45,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "DeepSeek R1 Distill 14B",
        "model_identifier": "deepseek-r1:14b",
        "temperature": 0.6,
        "max_tokens": 128000,
        "credits": 15,
        "input_tokens_cost": 0.30,
        "output_tokens_cost": 0.30,
        "completion": True,
        "embedding": False,
        "image_completion": False,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Llama 3.2 Vision",
        "model_identifier": "llama3.2-vision:11b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 55,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },

    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen 3.5 9B",
        "model_identifier": "qwen3.5:9b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 65,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Qwen3 VL 8B",
        "model_identifier": "qwen3-vl:8b",
        "temperature": 0.7,
        "max_tokens": 131072,
        "credits": 10,
        "input_tokens_cost": 0.20,
        "output_tokens_cost": 0.20,
        "completion": True,
        "embedding": False,
        "image_completion": True,
        "image_generation": False,
        "reasoning": True,
        "enabled": True,
        "rank": 70,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },

    # ===================== OLLAMA – EMBEDDINGS =====================
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "Nomic Embed v1.5",
        "model_identifier": "nomic-embed-text:latest",
        "temperature": 0.0,
        "max_tokens": 8192,
        "credits": 1,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 40,
        "tier": 5,
        "icon": ICON_OLLAMA,
    },
    {
        "service": AiServiceProvider.OLLAMA,
        "name": "BGE Large English v1.5",
        "model_identifier": "znbang/bge:large-en-v1.5-q4_k_m",
        "temperature": 0.0,
        "max_tokens": 512,
        "credits": 1,
        "input_tokens_cost": 0.04,
        "output_tokens_cost": 0.0,
        "completion": False,
        "embedding": True,
        "image_completion": False,
        "image_generation": False,
        "reasoning": False,
        "enabled": True,
        "rank": 35,
        "tier": 5,
        "icon": ICON_OLLAMA,
    }
]


async def main():
    # Init system DB
    await init_system_db()

    # Cleanup and insert tiers
    await Tier.delete_all()
    for tier_data in TIERS:
        tier = Tier(**tier_data)
        await tier.insert()
    logger.success(f"Tiers initialized: {len(TIERS)} tiers added.")

    # Cleanup AI models collection
    await AiModel.delete_all()

    # Insert AI models
    for model_data in AI_MODELS:
        ai_model = AiModel(**model_data)
        await ai_model.insert()

    logger.success(f"AI Models initialized: {len(AI_MODELS)} models added.")


if __name__ == "__main__":
    asyncio.run(main())